version: '3'

services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: phillippasswd

  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - "8123:80"
    depends_on:
      - db
